{{- if .Values.kubeploy.githubContainerRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubeploy.githubContainerRegistry.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"ghcr.io\":{\"username\":\"%s\",\"password\":\"%s\"}}}" .Values.kubeploy.githubContainerRegistry.username .Values.kubeploy.githubContainerRegistry.password | b64enc }}
{{- end }}