apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-registry
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.localRegistry.replicas }}
  selector:
    matchLabels:
      app: local-registry
  template:
    metadata:
      labels:
        app: local-registry
    spec:
      containers:
        - name: registry
          image: {{ .Values.localRegistry.image.repository }}:{{ .Values.localRegistry.image.tag }}
          ports:
            - containerPort: {{ .Values.localRegistry.service.port }}
          volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            {{- if .Values.localRegistry.auth.htpasswd }}
            - name: auth
              mountPath: /auth
              readOnly: true
            {{- end }}
          env:
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/tls.key
            {{- if .Values.localRegistry.auth.htpasswd }}
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            {{- end }}
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.localRegistry.tls.secretName }}
        {{- if .Values.localRegistry.auth.htpasswd }}
        - name: auth
          secret:
            secretName: registry-auth
            items:
              - key: htpasswd
                path: htpasswd
        {{- end }}