apiVersion: v1
kind: Service
metadata:
  name: local-registry
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: local-registry
  ports:
    - port: 443
      targetPort: {{ .Values.localRegistry.service.port }}