apiVersion: v2
name: kubeploy
description: A Helm chart for Kubeploy
version: 0.1.3
appVersion: '1.0.0'
dependencies:
  - name: cert-manager
    version: v1.12.0
    repository: https://charts.jetstack.io
    condition: certManager.enabled
  - name: ingress-nginx
    version: 4.7.1
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingressNginx.enabled
