namespace: kubeploy

serviceAccount:
  name: kubeploy-sa

clusterRole:
  name: kubeploy-role

clusterRoleBinding:
  name: kubeploy-role-binding

persistentVolumeClaim:
  name: postgres-data
  storage: 1Gi

kubeploy:
  image:
    repository: ghcr.io/typper-io/kubeploy
    tag: latest
    pullPolicy: Always
  replicas: 1
  githubContainerRegistry:
    enabled: true
    secretName: github-container-registry-auth
    username: 'your-github-username'
    # You should use a personal access token instead of your password with the following permissions:
    # - read:packages
    # - write:packages
    # - delete:packages
    password: 'your-github-personal-access-token'

  env:
    DATABASE_URL: 'postgresql://postgres:password@localhost:5432/kubeploy'

    # Used for github oauth
    GITHUB_SECRET: 'your-github-secret'
    GITHUB_ID: 'your-github-id'

    # Used for next-auth
    NEXTAUTH_SECRET: 'your-next-auth-secret'
    NEXTAUTH_URL: 'http://localhost:3000'

    INSTANCE_ADMIN_EMAIL: 'your-email'
    LETSENCRYPT_EMAIL: 'your-email'
    DEFAULT_NAMESPACE: 'kubeploy'
    NODE_ENV: 'development'

    # Used for github webhook
    APP_DOMAIN: 'localhost'
    WEBHOOK_SECRET: 'your-github-webhook-signature'

    # Used for cloning repositories
    GITHUB_USERNAME: 'your-github-username'
    GITHUB_PASSWORD: 'your-github-password-or-personal-access-token'

postgres:
  image:
    repository: postgres
    tag: '13'
  env:
    POSTGRES_DB: kubeploy
    POSTGRES_USER: postgres # You should change this
    POSTGRES_PASSWORD: password

service:
  name: kubeploy-service
  port: 80
  targetPort: 3000

certManager:
  enabled: true

ingressNginx:
  enabled: true
